builds dataworks base ami from hcs gold image

diff --git a/ci/infra/meta.yml b/ci/infra/meta.yml
--- a/ci/infra/meta.yml
+++ b/ci/infra/meta.yml
@@ -186,6 +186,10 @@ meta:
               cat packer-config/packer.json
               packer validate packer-config/packer.json
               AMI_ID="$(packer build -on-error=cleanup packer-config/packer.json | grep "${AWS_DEFAULT_REGION}:" | awk '{print $2}')"
+              if [ -z "$AMI_ID" ]; then
+                echo "packer build was failed."
+                exit 1
+              fi
               echo "${AMI_ID}" > built-ami/id
 
     proxy-test:
